Everything is working!
vincecanisius/Processing pull request #3
Opened 2020-10-26 21:33 UTC by vincecanisius

Bars & rectangles are all working together with the potmeters.

2020-10-26 21:39 UTC, mgovers requested changes
paar kleine details

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
> +int w = 450;
hier kun je beter floats van maken

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
>  int BPM = 0;                                                                     // Creating BPM var 0 as starting point
je kunt nog eens kijken hoe het eruit ziet als je hier weer `float` van maakt. kan zijn dat je op een paar plaatsen soortgelijke veranderingen moet maken maar dat is better practice

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
> +  sample = new FilePlayer( minim.loadFileStream("The Chemical Brothers - Got To Keep On.mp3") );      // Import the choosen .mp3 file to use in the code
```suggestion
  sample = new FilePlayer( minim.loadFileStream("The Chemical Brothers - Got To Keep On.mp3") );      // Import the desired .mp3 file to use in the code
```

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
> +  volumeControl = new Gain(0.f);                                                 // Creating volume controller
```suggestion
  volumeControl = new Gain(0.f);                                                 // Create volume controller
```

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
> +  rateControl = new TickRate(1.f);                                               // Creating BPM controller
```suggestion
  rateControl = new TickRate(1.f);                                               // Create BPM controller
```

2020-10-26 21:39 UTC, mgovers commented on prutsen/prutsen.pde
> +  r_BPM = r_BPM + map(BPM, 0, maxBPM, 0, max_rotation_speed);
ev kun je dit in aparte functie zetten, `draw_rotating_bars` ofzo, en dan die for loops in `draw_center_bars`

2020-10-27 17:10 UTC, mgovers requested changes
typos

2020-10-27 17:10 UTC, mgovers commented on prutsen/prutsen.pde
> +float z = 650;                                                                   // Creating float Z with calue 650
```suggestion
float z = 650;                                                                   // Creating float Z with value 650
```

2020-10-27 17:10 UTC, mgovers commented on prutsen/prutsen.pde
> +float y = 450;                                                                   // Creating flpat Y with vlua 450
```suggestion
float y = 450;                                                                   // Creating float Y with value 450
```

2020-10-27 17:10 UTC, mgovers commented on prutsen/prutsen.pde
> +float r_BPM = 0;                                                                 // Creating float r_BPM with value 0
je kunt misschien beter comments maken als 'x position of rotating volume bar' en 'rotation angle (degrees) of volume bar'

2020-10-27 17:10 UTC, mgovers commented on prutsen/prutsen.pde
> +float max_rotation_speed = 100;                                                  // Creating gloat max_rotation_speed with value 100
```suggestion
float max_rotation_speed = 100;                                                  // Creating float max_rotation_speed with value 100
```

2020-10-27 17:11 UTC, mgovers commented on prutsen/prutsen.pde
> +  r_BPM = r_BPM + map(BPM, 0, maxBPM, 0, max_rotation_speed);
toch maar niet gedaan? 😛

2020-10-27 17:42 UTC, vincecanisius commented
100% comitted

2020-10-27 17:42 UTC, merged